# ===========================================================
# NAVIGATION
# ===========================================================

nav:
  - Home: README.md
  - My apps: pages/my_apps.md
  - About: about.md
  - My cheatsheet: cheatsheet.md
  - My links: links.md
  - Docs: https://docs.alnoda.org/

# ===========================================================
# CONFIGURATION
# ===========================================================

site_name: My Workspace
repo_url: https://github.com/bluxmit/alnoda-workspaces
site_url: https://alnoda.org
edit_uri: ""

# ===========================================================
# APPEARANCE
# ===========================================================

theme:
  name: 'material'
  favicon: 'assets/laptop-circle.svg'
  logo: 'assets/laptop-circle-white.svg'
  custom_dir: overrides
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
  palette:
    - scheme: workspace
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: workspace-dark
      toggle:
        icon: material/brightness-4
        name: Switch to light mode 

extra:
  # Link to open when your logo is clicked
  homepage: https://alnoda.org
  host_url: http://alnoda.org

plugins:
  # Enable Macros and jinja2 templates
  - macros:
      module_name: macros/helpers

extra_css:
  - stylesheets/extra.css
  - stylesheets/quickstart.css

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6

